version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:17-alpine

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run: gradle dependencies
      - run: gradle test
